// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzdKTeWXUUW4Am_jLY31zQJFWebTyAQLM',
    appId: '1:130961774622:web:8ca2b570fd5603bec3760f',
    messagingSenderId: '130961774622',
    projectId: 'zenmobeta',
    authDomain: 'zenmobeta.firebaseapp.com',
    storageBucket: 'zenmobeta.appspot.com',
    measurementId: 'G-WXW0D7J2NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQlPjL9r9L2FbyaJcKtmXaVBoJ2eRTUWQ',
    appId: '1:130961774622:android:421392c0efa924b1c3760f',
    messagingSenderId: '130961774622',
    projectId: 'zenmobeta',
    storageBucket: 'zenmobeta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7kSKJIoay8RGZVF22aU5KdHjCET4Mz6A',
    appId: '1:130961774622:ios:4e850958e63367d5c3760f',
    messagingSenderId: '130961774622',
    projectId: 'zenmobeta',
    storageBucket: 'zenmobeta.appspot.com',
    iosBundleId: 'com.example.colorWallet',
  );
}
